### PR TITLE
Status bar applet

### LINKED ISSUE #68: [Feature] Menubar icon for starting/stopping server

### PR DESCRIPTION
**Pull request by thomassnielsen**
Adds a status bar applet for running and stopping the server. This also includes a global hot key.

Fixes #68

The current icon looks like this (it's the `e`, other icons included for scale):

skjermbilde 2015-04-26 kl 13 01 00
skjermbilde 2015-04-26 kl 13 01 24

@kimroen is this good enough to join 0.3.0, or should we put some more work into the icon?

### CODE REVIEW

**Comment by kimroen** [comment]
Seems useful - nice!

Some things:
- I'm not sure about the color - the red seems to make it slightly lighter than it should be, but that could just be me
- The size doesn't feel right, but I'll have to check the HIG for some info on that. It's fine for now. (we'll need a new one eventually, but that's farther off)
- I don't think it's cool to just register a global hotkey if the user can't redefine it (or see what it is!)
- When you start the server from the applet with a different window in the foreground (like the browser), there is no indication that anything is happening. We need _some kind_ of response
- There should probably be some setting to not show the applet. It's a secondary thing

So - things we could do right now or make issues for and do later:
- Show the shortcut in settings, or better yet allow the user to redefine it. It looks like the MASShortcuts pod has some stuff for it, as far as I can see.
- Consider a setting to not show the applet.
- Consider what kind of response would be appropriate when the server is starting

**Comment by thomassnielsen** [comment]
- What color? The red of the `e` menu bar icon? It's used as a template anyway, so the color doesn't matter. It should be the same as the logo, I opened into Pixelmator and cut it to fit.
- Agree about the sizing details, for now I eyeballed it close to the rest of my status bar. Might be a pixel or two off.
- If we put a setting for the hotkey in settings, should we default to something or nothing?
- How about using notifications for when the server is starting? That would be even more important for hotkey use, I imagine.
- Another setting, got it.

**Comment by thomassnielsen** [comment]
How does this look?

skjermbilde 2015-04-26 kl 15 57 07

skjermbilde 2015-04-26 kl 15 57 22

**Comment by kimroen** [comment]
Awesome!

> What color? The red of the e menu bar icon? It's used as a template anyway, so the color doesn't matter. It should be the same as the logo, I opened into Pixelmator and cut it to fit.

I was thinking about the gray of the logo, imagining it was based on the lightness value of the red color, but maybe it's not based on that after all.

> If we put a setting for the hotkey in settings, should we default to something or nothing?

I think having a default is fine.

> How about using notifications for when the server is starting? That would be even more important for hotkey use, I imagine.

I think being clear about that the server is starting might be even more important than the fact that it started, and I don't think notifications is great for that. The notification you show there for "started" is good.

> Another setting, got it.

:heart:

**Comment by kimroen** [comment]
The default shortcut is [pretty brutal](https://news.ycombinator.com/item?id=313369) though.

**Comment by thomassnielsen** [comment]
> I was thinking about the gray of the logo, imagining it was based on the lightness value of the red color, but maybe it's not based on that after all.

Doesn't seem like it, we get the same gray as twitter and dropbox (and more). There is a slight fuzz around it though, which is due to my immense graphic design skill (or lack there of).

> I think being clear about that the server is starting might be even more important than the fact that it started, and I don't think notifications is great for that.

What about when you start the server through a hot key? The only other option I can think of that works in that case is doing something to the status bar icon, but that is both optional and subtle. 

Currently I've disabled notifications for starting the server, but showing for stated/stopped/error. I'm also debating in my mind the usefulness of showing the stopped notification, as it happens immediately. An option (which would work for "starting" as well) is to only show certain notifications if the app is in the background. Thoughts?

**Comment by kimroen** [comment]
> An option (which would work for "starting" as well) is to only show certain notifications if the app is in the background.

Only when in the background is a good idea either way I think, as we have (and should have where we don't) indicators of that activity in the main interface.

I still don't think a notification is good for "starting". We just need an indication that something is happening when you click the thing, not a notification that something happened. An indicator in the menu bar is probably the way to go.

How about something like what Time Machine does? They have a little play icon within the Time Machine icon when a backup is happening.

Suggestion:

suggested icons
1. Server idle
2. Server starting
3. Server running

Don't mind the execution, just trying to communicate the idea.

**Comment by thomassnielsen** [comment]
Agree, sounds like a good idea. 

I like the suggestion, although the circle may be a bit low, as it will be below the baseline of most icons. 

You can test it out by adding it to the Images.xcassets bundle and editing `showStatusBarItem()` in the app delegate. If you want to test out the different ones, check out `serverStarting()` and friends further down, which gets called when the server status changes.

**Comment by kimroen** [comment]
Ended up with something like this:

**Pull request merged**
