### PR TITLE
Allows stopping of server before it is fully started

### LINKED ISSUE #64: Allow canceling running of server
This operation may take a while for big projects, so we should allow canceling. Can be implemented by terminating the running task. We need a new way to indicate that the server is starting, since today we disable the button and put a progress indicator above it.

### PR DESCRIPTION
**Pull request by thomassnielsen**
Fixes #64

Changes:
- Makes open in browser visible/hidden instead of enabled/disabled
- Moves progress indicator to the side
- Never disables run/stop button

Animating illustration

@kimroen what do you think of this design wise? IMO it is a lot better than what we have, but do you have any suggestions at the top of your head that would make it even better?

### CODE REVIEW

**Comment by kimroen** [comment]
Where did "open in browser" go?

I think this is a lot better :+1:

**Comment by thomassnielsen** [comment]
Open in browser is now hidden until the server is running (gif doesn't show it in the running state). It replaces the loading spinner in place where it used to be.

**Comment by thomassnielsen** [comment]
Go ahead to merge?

**Comment by kimroen** [comment]
Sounds good. Go for it.

**Pull request merged**
